spring:
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/ecommerce
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  devtools:
    restart:
      enabled: false
  mail:
    host: localhost
    port: 25
encryption:
  salt:
    rounds: 5
jwt:
  algorithmKey: SuperSecuredSecrete
  issuer: Ecommerce
  expiresInSeconds: 640800
email:
  from: Ecommerce
app:
  frontend:
    url: https://frontend.com